apiVersion: v1
kind: Service
metadata:
  labels:
    app: menu-backend
  name: menu-backend
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: menu-backend
  type: ClusterIP
